done init
['rtm', '재기동']
Sucessfully heard.
['재기동']
['rtm', '현재상황']
Sucessfully heard.
['현재상황']
['New13579!']
Sucessfully heard.
['장애!']
Sucessfully heard.
['ㅁㅁㅁㅁㅁ']
Sucessfully heard.
['https://www.elastic.co/kr/blog/introducing-machine-learning-for-the-elastic-stack']
Sucessfully heard.
['https://gist.github.com/haje01/202ac276bace4b25dd3f']
Sucessfully heard.
['텐서플로우로', '손글씨', '매핑하는', '거', '샘플']
Sucessfully heard.
['ㅇㅇ']
Sucessfully heard.
['ㄹㄹㄹ']
Sucessfully heard.
['https://monbot.hopto.org:3000/d/z2yCOGpWz/docker-and-system-monitoring?orgId=1&refresh=5m&from=1568903364089&to=1568989764089&var-containergroup=All&var-interval=$__auto_interval_interval&var-server=', 'link']
Sucessfully heard.
['https://monbot.hopto.org:3000/dashboard/snapshot/yemPROHe0GzZFf9NqUYlasLqoLjXwnr4', 'snapshot']
Sucessfully heard.
['aaa']
Sucessfully heard.
['rtm', 'ao']
Sucessfully heard.
['ao']
['[zulip-org-logo.png](/user_uploads/3/9d/NGPaAQsGD2J99BZS2RgaQbGZ/zulip-org-logo.png)']
Sucessfully heard.
['[zulip-org-logo.png](/user_uploads/3/45/j3XN2ZRD-Ykglv9yRY0dV46N/https_monbot.hopto.org_3000_dashboard_snapshot_yemPROHe0GzZFf9NqUYlasLqoLjXwnr4_orgId_1_refresh_5m.png)']
Sucessfully heard.
['[zulip-org-logo.png](/user_uploads/3/a1/yshVogNpTXZmyHDF9tO6OeAi/zulip-org-logo.png)']
Sucessfully heard.
['[zulip-org-laaaogo.png](/user_uploads/3/a1/yshVogNpTXZmyHDF9tO6OeAi/zulip-org-logo.png)']
Sucessfully heard.
['rtm']
Sucessfully heard.
Traceback (most recent call last):
  File "bot.py", line 65, in <module>
    main()
  File "bot.py", line 61, in main
    bot.client.call_on_each_message(bot.process)
  File "/home/zulip/.local/lib/python3.6/site-packages/zulip/__init__.py", line 696, in call_on_each_message
    self.call_on_each_event(event_callback, ['message'])
  File "/home/zulip/.local/lib/python3.6/site-packages/zulip/__init__.py", line 688, in call_on_each_event
    callback(event)
  File "/home/zulip/.local/lib/python3.6/site-packages/zulip/__init__.py", line 695, in event_callback
    callback(event['message'])
  File "bot.py", line 46, in process
    "content": content[1]
IndexError: list index out of range
/home/zulip/.local/lib/python3.6/site-packages/urllib3/connectionpool.py:1004: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning,
/home/zulip/.local/lib/python3.6/site-packages/urllib3/connectionpool.py:1004: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning,
done init
['rtm', 'snapshot']
Sucessfully heard.
1_
b'{"message":"Logged in"}'
2_
Traceback (most recent call last):
  File "izyrtm.py", line 81, in <module>
    main()
  File "izyrtm.py", line 77, in main
    bot.client.call_on_each_message(bot.process)
  File "/home/zulip/.local/lib/python3.6/site-packages/zulip/__init__.py", line 696, in call_on_each_message
    self.call_on_each_event(event_callback, ['message'])
  File "/home/zulip/.local/lib/python3.6/site-packages/zulip/__init__.py", line 688, in call_on_each_event
    callback(event)
  File "/home/zulip/.local/lib/python3.6/site-packages/zulip/__init__.py", line 695, in event_callback
    callback(event['message'])
  File "izyrtm.py", line 44, in process
    timestamp = int(time.time()*1000.0)
NameError: name 'time' is not defined
/home/zulip/.local/lib/python3.6/site-packages/urllib3/connectionpool.py:1004: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning,
done init
['rtm', 'snapshot', 'cmem']
Sucessfully heard.
1_
b'{"message":"Logged in"}'
Traceback (most recent call last):
  File "izyrtm.py", line 101, in <module>
    main()
  File "izyrtm.py", line 97, in main
    bot.client.call_on_each_message(bot.process)
  File "/home/zulip/.local/lib/python3.6/site-packages/zulip/__init__.py", line 696, in call_on_each_message
    self.call_on_each_event(event_callback, ['message'])
  File "/home/zulip/.local/lib/python3.6/site-packages/zulip/__init__.py", line 688, in call_on_each_event
    callback(event)
  File "/home/zulip/.local/lib/python3.6/site-packages/zulip/__init__.py", line 695, in event_callback
    callback(event['message'])
  File "izyrtm.py", line 62, in process
    response = call.getSnapShot(sessionId, panelId, '', '')
  File "/home/zulip/izyrtm/rtmBot/call.py", line 35, in getSnapShot
    snapShotUrl = 'https://monbot.hopto.org:3000/render/dashboard-solo/db/docker-and-system-monitoring?orgId=1&panelId='+panelId+'&from='+startDate+'&to='+endDateMil+'&width=1000&height=500'
TypeError: must be str, not datetime.datetime
